// C2.2 — Streaming body filter: strip comment lines (starting with #)
//
// The 'streaming' body filter receives an async-iterable of body chunks.
// We accumulate them, split on newlines, filter out comment lines, and
// yield the cleaned text as a single chunk.
//
// /data/         — returns text with embedded comments; filter strips them
// /passthrough/  — same raw text, no filter (for comparison)

(function () {
    var server = nginx.http.servers[0];

    var RAW_BODY = [
        '# This file was generated by config-gen v2.1',
        '# DO NOT EDIT MANUALLY',
        '',
        'host=db.internal',
        'port=5432',
        '',
        '# Connection pool settings',
        'pool_min=2',
        'pool_max=20',
        '',
        '# Timeout (ms)',
        'connect_timeout=3000',
        'query_timeout=10000',
        '',
        'debug=false',
        ''
    ].join('\n');

    // /passthrough/ — raw output, comments included
    var passLoc = server.findLocation('/passthrough/');
    passLoc.handler = function (r) {
        r.respond(200, { 'Content-Type': 'text/plain' }, RAW_BODY);
    };

    // /data/ — handler emits raw body; filter strips comment lines
    var dataLoc = server.findLocation('/data/');

    dataLoc.handler = function (r) {
        r.respond(200, { 'Content-Type': 'text/plain' }, RAW_BODY);
    };

    // Generator filter: accumulate chunks, strip comment lines
    // API: addBodyFilter('generator', async function*(chunks, r) { ... })
    dataLoc.addBodyFilter('generator', async function* (chunks, r) {
        var buf = '';
        for await (var chunk of chunks) {
            buf += chunk;
        }

        var lines  = buf.split('\n');
        var kept   = lines.filter(function (line) {
            return !line.startsWith('#');
        });

        // Also compress consecutive blank lines into one
        var out = [];
        var prevBlank = false;
        kept.forEach(function (line) {
            var blank = line.trim() === '';
            if (blank && prevBlank) return;
            out.push(line);
            prevBlank = blank;
        });

        yield out.join('\n');
    });
}());
