worker_processes  2;          # 2 nginx workers => the SharedWorker aggregates
pid               logs/nginx.pid;
error_log         logs/error.log  info;

js_source         handler.js;

events {
    worker_connections  256;
}

http {
    default_type  application/json;

    server {
        listen       8234;
        server_name  localhost;

        location /task/    { }
        location /global/  { }
    }
}
