pid        nginx-repl-demo/nginx.pid;
error_log  nginx-repl-demo/error.log info;
daemon     off;
worker_processes 4;

js_source nginx-repl-demo/repl.js;

events { worker_connections 1024; }

http {
    server {
        listen 127.0.0.1:8099;
        server_name localhost;

        location /repl/ { }
    }
}
