worker_processes  1;
pid               logs/nginx.pid;
error_log         logs/error.log  info;

js_source         handler.js;

events {
    worker_connections  256;
}

http {
    default_type  text/plain;

    server {
        listen       8106;
        server_name  localhost;

        location /data/            { }
        location /admin/snapshot/  { }
        location /admin/change/    { }
        location /admin/rollback/  { }
        location /admin/status/    { }
    }
}
