#!/usr/bin/perl

# Tests for js_preprocess directive — JS config preprocessor.
#
# js_preprocess runs JS mid-parse (before init_conf); the script calls
# config.write(text) to inject nginx directives as if they appeared
# inline in nginx.conf.  The JS runtime is short-lived and isolated
# from the js_include runtime.
#
# Tests covered:
#   - Basic: config.write() generates http{}/server{}/location{}
#   - JS can call config.write() multiple times in a single script
#   - Generated config can include multiple servers on different ports
#   - nginx.conf needs no http{} block of its own

use warnings;
use strict;
use Test::More;

BEGIN { use FindBin; chdir($FindBin::Bin); }
use lib 'lib';
use Test::Nginx;

select STDERR; $| = 1;
select STDOUT; $| = 1;

my $t = Test::Nginx->new()->has(qw/http rewrite/);

# nginx.conf: only top-level boilerplate + js_preprocess.
# The entire http{} block is generated by the JS script.

$t->write_file_expand('nginx.conf', <<'EOF');
%%TEST_GLOBALS%%
daemon off;

js_preprocess %%TESTDIR%%/preprocess.js;

events { }
EOF

# preprocess.js — calls config.write() twice to emit two separate
# server blocks (different ports, different locations).

$t->write_file_expand('preprocess.js', <<'JS');
// First call: http block containing two servers.
// We open and close the entire http{} block in one write.
config.write(`
    http {
        %%TEST_GLOBALS_HTTP%%

        server {
            listen       127.0.0.1:8080;
            server_name  localhost;

            location /hello/ {
                return 200 "Hello from JS preprocessor";
            }

            location /world/ {
                return 200 "World";
            }
        }

        server {
            listen       127.0.0.1:8081;
            server_name  localhost;

            location /second/ {
                return 200 "Second server";
            }
        }
    }
`);
JS

$t->try_run('no js module')->plan(8);


# --- Server 1 (port 8080) ---

like(http_get('/hello/'),
     qr|200 OK|,
     'generated location /hello/ responds 200');

like(http_get('/hello/'),
     qr|Hello from JS preprocessor|,
     'generated location /hello/ body correct');

like(http_get('/world/'),
     qr|200 OK|,
     'generated location /world/ responds 200');

like(http_get('/world/'),
     qr|World|,
     'generated location /world/ body correct');


# --- Server 2 (port 8081) ---

like(http_get('/second/', PeerAddr => '127.0.0.1:8081'),
     qr|200 OK|,
     'second generated server responds 200');

like(http_get('/second/', PeerAddr => '127.0.0.1:8081'),
     qr|Second server|,
     'second generated server body correct');


# --- Verify js_include still works alongside js_preprocess ---
# (Both directives can coexist; js_include runs after full parse)

like(http_get('/hello/'),
     qr|200 OK|,
     'js_preprocess does not break basic request handling');

like(http_get('/second/', PeerAddr => '127.0.0.1:8081'),
     qr|200 OK|,
     'second server still responds after repeated requests');
