worker_processes  1;
pid               logs/nginx.pid;
error_log         logs/error.log  info;
js_source         handler.js;

events { worker_connections 256; }

http {
    default_type  application/json;

    server {
        listen       8167;
        server_name  localhost;

        location /canary/          { }
        location /internal/stable/ { internal; }
        location /internal/canary/ { internal; }
        location /admin/enable-canary/   { }
        location /admin/disable-canary/  { }
        location /admin/canary-status/   { }
    }
}
