worker_processes  1;
pid               logs/nginx.pid;
error_log         logs/error.log  info;

js_source         handler.js;

events {
    worker_connections  256;
}

http {
    default_type  text/plain;

    server {
        listen       8107;
        server_name  localhost;

        location /beta/         { }
        location /stable/       { }
        location /admin/toggle/ { }
        location /admin/flags/  { }
    }
}
